In [3]:
import numpy as np
import pandas as pd

# Dynamic Programming Examples

Dynamic programming is an algorithm design technique that helps you 

> **Common subproblems**

> 1. The input is $x_1, x_2, ... , x_n$ and the subproblem is $x_1, x_2, ... , x_i$. 
The number of subproblems is $O(n)$.

> 2. The input is $x_1, ... , x_n$ and $y_1, ... , y_n$. A subproblem is $x_1, ... , x_i$ and $y_1, ... , y_i$. The number of subproblems is $O(nm)$

> 3. The input is $x_1, ... , x_n$ and a subproblem is $x_i, x_{i+1}, ... , x_j$. The number of subproblems is $O(n^2)$

## Knapsack (without repetition)
You are given a knapsack that holds a total of $W$ pounds. There are $n$ items to choose from, of weights $w_1, w_2, ..., w_n$ and values $v_1, v_2, ..., v_n$. What is the most valuable combination you can fit into your bag? 

### Definition
Define K(i,j) to be the maximum value achieved from using items $x_1, x_2, ... , x_i$ with weight equal to $w_j$. 

### Recurrence
$$\left\{\begin{matrix}
max\{K(i-1, j-x_i) + x_i, K(i-1, j)\} & if \quad j \geq x_i\\ 
K(i-1, j) & if \quad j < x_i
\end{matrix}\right.$$

### Runtime analysis
$$O(nW)$$

In [4]:
def knapsack_no_rep(W, x):
    n = len(x) + 1
    w = np.arange(W+1)
    
    K = np.zeros((n, len(w)))
    
    for i in range(1, n):
        for j in range(1, len(w)):
            if j >= x[i-1][0]:
                K[i, j] = max(K[i-1, j-x[i-1][0]] + x[i-1][1], K[i-1, j])
            else:
                K[i, j] = K[i-1, j]

    return K[-1, -1]

In [5]:
W = 10
x = [(6, 30), (3, 14), (4, 16), (2, 9)]  # each item in x represents (weight, value)
print(knapsack_no_rep(W, x))

46.0


## Knapsack (with repetition)
You are given a knapsack that holds a total of $W$ pounds. There are $n$ items to choose from, of weights $w_1, w_2, ..., w_n$ and values $v_1, v_2, ..., v_n$. What is the most valuable combination you can fit into your bag *when you are allowed to use an item more than once*? 

### Definition
Define K(w) to be the maximum value with a knapsack of weight $w$ achieved from using items $x_1, x_2, ... , x_n$. 

### Recurrence
$$\max _{i:w_j \leq w}\{K(w-w_i) + v_i\}$$

### Runtime analysis
$$O(nW)$$

In [6]:
def knapsack_rep(W, x):
    
    K = np.zeros(W+1)
    
    for i in range(1, W+1):
        values = [0]
        for j in range(len(x)):
            if x[j][0] <= i:
                values.append(K[i-x[j][0]] + x[j][1])
        K[i] = max(values)
    
    return K[-1]

In [7]:
W = 10
x = [(6, 30), (3, 14), (4, 16), (2, 9)]  # each item in x represents (weight, value)
print(knapsack_rep(W, x))

48.0


## Palindrome length
Create an algorithm that takes in a sequence x[1..n] and returns the length of the longest palindromic subsequence. The run time should be $O(n^2)$.

### Definition
Define $a'$ to be the reverse of string $a$.
Let L(i,j) be the length of the longest palindromic length in string in $a_1, a_2, ..., a_i$ and $a'_1, a'_2, ... a'_j$ where both $a_i$ and $a'_j$ are included.

### Recurrence
$$\left\{\begin{matrix}
0 & if \quad a_i \neq a'_j\\ 
1 + L(i-1, j-1) & if \quad x_i = y_j
\end{matrix}\right.$$

### Runtime analysis
Because this algorithm has two nested for loops of length n, the runtime is as follows $$O(n^2)$$

In [8]:
def palindrome(s):
    n = len(s) + 1
    s_prime = s[::-1]  # reverse s
    
    L = np.zeros((n, n))
    
    for i in range(1, n):
        for j in range(1, n):
            if s[i-1] == s_prime[j-1]:
                L[i, j] = 1 + L[i-1, j-1]
            else:
                L[i, j] = 0
    
    return L.max()

In [9]:
s = 'aabbbcsbcbsab'
print(palindrome(s))

5.0


## Common Sub*?!* length
Given two strings X = $x_1, x_2, ... x_n$ and Y = $y_1, y_2, ... y_m$ give an algorithm to find the length k of the longest string Z appears as a *substring* of X and a *subsequence* of Y. 

### Definition
Let L(i,j) be the length of the longest common sub*?!* in $x_1, x_2, ... , x_i$ and $y_1, y_2, ... y_j$ where both $x_i$ and $y_i$ are included.


### Recurrence
$$\left\{\begin{matrix}
0 & if \quad x_i = 0 \quad or \quad y_j = 0\\ 
1 + L(i-1, j-1) & if \quad x_i = y_j\\ 
L(i, j-1) & if \quad x_i \neq y_j
\end{matrix}\right.$$

### Runtime analysis
This algorithm has two nested for loops of length n and m, therefore the runtime is as follows: $$O(nm)$$

In [10]:
def LCS_variant(x, y):
    n = len(x) + 1
    m = len(y) + 1
    
    L = np.zeros((n, m))
    
    for i in range(1, n):
        for j in range(1, m):
            if x[i-1] == y[j-1]:
                L[i, j] = 1 + L[i-1, j-1]
            else:
                L[i, j] = L[i, j-1]
    
    return L[:,-1].max()

In [11]:
x = ['a', 'b', 'd', 'b', 'a', 'b', 'f', 'g', 'd']
y = ['b', 'e', 't', 'f', 'd', 'b', 'f', 'a', 'f', 'r']

print(LCS_variant(x, y))

4.0


## Maximum Product
Given a string of integers Z = $z_1, z_2, ... , z_n$ and an integer $k$ where $0 \leq k < n$, maximize the mathematical result of the string by adding *exactly* $k$ operators. 

### Definition
Let P(i,k) be the maximum product made from $z_1, z_2, ... , z_i$ with k multiplication operators and where $z_i$ and $k$ are included. 

### Recurrence
$$\left\{\begin{matrix}
z(1:i) & if \quad k=0\\ 
0 & if \quad i \leq k\\ 
max_l\{z(l+1, i)*P(l,k-1): k \leq l < i\} & if \quad otherwise
\end{matrix}\right.$$

### Runtime analysis
This algorithm has three nested for loops of the following runtimes $O(n)$, $O(k)$, $O(n)$, therefore we have a final runtime of $$O(n^2k)$$

In [12]:
def maximum_product(z, k):
    n = len(z) + 1
    m = k+1
    
    P = np.zeros((n, m))
    P[1:, 0] = [int(z[:i+1]) for i in range(len(z))]
    
    for i in range(1, n):
        for j in range(1, m):
            if i > j:
                max_l = j
                for l in range(j, i):
                    if int(z[l:i]) * P[l, j-1] > int(z[max_l:i]) * P[max_l, j-1]:
                         max_l = l
                P[i, j] = int(z[max_l:i]) * P[max_l, j-1]
    
    return P[-1, -1]

In [13]:
z = str(84738)
k = 3

print(maximum_product(z, k))

18688.0


## Change coin variant
You are given denominations $x_1, x_2, ... , x_n$ and you want to make change for a value B. You can only use at most $k$ coins and use each denomination at most once. 

### Definition
Let C(i,b) = the minimum number of coins who add up to exactly $b_i$.

### Recurrence
$$\left\{\begin{matrix}
min\{C(i-1, b-x_i) + 1, C(i-1, b)\} & if \quad x_i \leq b\\ 
C(i-1,b) & if \quad x_i > b
\end{matrix}\right.$$

### Runtime analysis
$$O(nB)$$

In [14]:
def change_coins(x, k, B):
    n = len(x) + 1
    b = np.arange(B+1)
    
    C = np.zeros((n, len(b)))
    C[0, 1:] = 999  # 999 represents infinity in this algorithm
    
    for i in range(1, n):
        for j in range(1, len(b)):
            if x[i-1] > b[j]:
                C[i,j] = C[i-1, j]
            else:
                C[i,j] = min(C[i-1, j-x[i-1]]+1, C[i-1, j])
                
    return C[-1,-1] <= k

In [15]:
x = [2, 2, 1, 3, 1, 1]
k = 3
B = 7

print(change_coins(x, k, B))

True


## Chain multiplication
Create an algorithm that minimizes the cost of multiplying $n$ matrices together by creating the optimal combination of parenthesize. Remember the cost of multiplying an $m x n$ matrix by an $n x p$ matrix takes $mnp$ multiplications. That is what we have defined as the *cost*. 

### Definition
Let C(i,j) represent the minimum cost for computing $A_i, A_{i+1}, ... , A_{j}$ matrices. 

### Recurrence
$$C(i,j) = \min_{i \leq l < j}[C(i,l) + C(l+1, j) + (m_{i-1}*m_l*m_j)]$$

### Runtime analysis


In [31]:
def chain_multiplication(M):
    N = len(M)
    
    C = np.zeros((N, N))
    
    # set base case
    for i in range(N):
        C[i, i] = 0
        
    for s in range(1,N-1):
        for i in range(1, N-s):
            j = i+s
            k_vals = []
            for k in range(i, j):
                k_vals.append(C[i, k] + C[k+1, j] + M[i-1]*M[k]*M[j])
            C[i,j] = min(k_vals)
    
    return C[1, -1]

In [32]:
M = [50, 20, 1, 10, 100]

print(chain_multiplication(M))

7000.0


## Optimal binary tree search
Create an algorithm that takes keyword frequencies and constructs a binary tree with the minimum cost of comparisons needed to find a word within the  tree.. 

### Definition
Let $C(i,j)$ represent the minimum average comparisons needed for $p_i, p_{i+1} ... , p_j$ frequencies. 

### Recurrence
$$C(i,j) = \min_{i \leq l < j}[C(i,l) + C(l+1, j) + (m_{i-1}*m_l*m_j)]$$

### Runtime analysis


In [79]:
def binary_tree_search(P):
    N = len(P)
    
    C = np.zeros((N, N))
    
    for i in range(1, N):
        C[i, i] = P[i]
    
    for s in range(1,N-1):
        for i in range(1, N-s):
            j = i+s
            k_vals = []
            for k in range(i, j+1):
                k_vals.append(C[i, k-1] + C[k+1, j] + sum(P[i:j+1]))
                print("i: {} j: {} sum: {}".format(i, j, sum(P[i:j+1])))
            C[i,j] = min(k_vals)
            print(C[i,j])
        
    return(C.T)

In [80]:
P = [0, 5, 40, 8, 4, 10, 10, 23]

print(binary_tree_search(P))

i: 1 j: 2 sum: 45
i: 1 j: 2 sum: 45
50.0
i: 2 j: 3 sum: 48
i: 2 j: 3 sum: 48
56.0
i: 3 j: 4 sum: 12
i: 3 j: 4 sum: 12
16.0
i: 4 j: 5 sum: 14
i: 4 j: 5 sum: 14
18.0
i: 5 j: 6 sum: 20
i: 5 j: 6 sum: 20
30.0
i: 6 j: 7 sum: 33


IndexError: index 8 is out of bounds for axis 0 with size 8

In [37]:
print(sum([40, 2*5, 2*23, 3*10, 4*8, 4*10, 5*4]))

218


# Testing algorithms

## Algorithm Design 6.2

In [100]:
def job_planning(l, h):
    l.insert(0, 0)
    h.insert(0, 0)
    n = len(l)
    
    V = np.zeros(n)
    
    for i in range(1, n):
        if i > 1:
            V[i] = max(h[i] + V[i-2], l[i] + V[i-1])
        else: 
            V[i] = l[i]
                
    print(V.T)
    
    return V[-1]

In [102]:
l = [10, 1, 10, 10]
h = [5, 50, 5, 10]

print(job_planning(l, h))

[  0.  10.  50.  60.  70.]
70.0


## Algorithm Design 6.4

In [120]:
def business_planning(ny, sf):
    ny.insert(0, 0)
    sf.insert(0, 0)
    n = len(ny)
    
    C = np.zeros(n)
    C[1] = min(ny[1], sf[1])
    
    for i in range(2, n):
        if C[i-1] - ny[i-1] == C[i-2]:
            C[i] = min(C[i-1] + ny[i], C[i-1] + sf[i] + 10)
        elif C[i-1] - sf[i-1] == C[i-2]:
            C[i] = min(C[i-1] + ny[i] + 10 , C[i-1] + sf[i])
        else:
            print("why")
    
    print(C.T)
    return C[-1]

In [121]:
ny = [1, 3, 20, 30]
sf = [50, 20, 2, 4]

print(business_planning(ny, sf))

why
[  0.   1.   4.  16.   0.]
0.0


## Algorithm Design 6.7

In [136]:
def profit(p):
    n = len(p)
    M = np.zeros(n)
    
    for i in range(1, n):
        if p[i-1] < p[i]:
            M[i] = M[i-1] + (p[i] - p[i-1])
        else:
            M[i] = 0

    return M.max()

In [137]:
a = [10, 15, 6, 3, 7, 12, 2, 9]
print(profit(a))

9.0


## Algorithm Design 6.8

In [148]:
def EMP(x, f):
    x.insert(0, 0)
    f.insert(0, 0)
    n = len(x)
    
    K = np.zeros(n)
    
    for i in range(1, n):
        options = []
        for j in (1, i):
            options.append(K[j-1] + min(x[i], f[i-(j-1)]))
        K[i] = max(options)
    
    print(K.T)
    return K[-1]

In [149]:
x = [1, 10, 10, 1]
f = [1, 2, 4, 8]

print(EMP(x, f))

[ 0.  1.  2.  4.  5.]
5.0


## Algorithm Design 6.8