In [5]:
import numpy as np
import pandas as pd

# Dynamic Programming Examples

Dynamic programming is...

## Palindrome length
Create an algorithm that takes in a sequence x[1..n] and returns the length of the longest palindromic subsequence. The run time should be $O(n^2)$.

### Definition
Define $a'$ to be the reverse of string $a$.
Let L(i,j) be the length of the longest palindromic length in string in $a_1, a_2, ..., a_i$ and $a'_1, a'_2, ... a'_j$ where both $a_i$ and $a'_j$ are included.

### Recurrence
$$\left\{\begin{matrix}
0 & if \quad a_i \neq a'_j\\ 
1 + L(i-1, j-1) & if \quad x_i = y_j
\end{matrix}\right.$$

### Runtime analysis
Because this algorithm has two nested for loops of length n, the runtime is as follows $$O(n^2)$$

In [18]:
def palindrome(s):
    n = len(s) + 1
    s_prime = s[::-1]  # reverse s
    
    L = np.zeros((n, n))
    
    for i in range(1, n):
        for j in range(1, n):
            if s[i-1] == s_prime[j-1]:
                L[i, j] = 1 + L[i-1, j-1]
            else:
                L[i, j] = 0
    
    return L.max()

In [17]:
s = 'aabbbcsbcbsab'
print(palindrome(s))

5.0


## Common Sub*?!* length
Given two strings X = $x_1, x_2, ... x_n$ and Y = $y_1, y_2, ... y_m$ give an algorithm to find the length k of the longest string Z appears as a *substring* of X and a *subsequence* of Y. 

### Definition
Let L(i,j) be the length of the longest common sub*?!* in $x_1, x_2, ... , x_i$ and $y_1, y_2, ... y_j$ where both $x_i$ and $y_i$ are included.


### Recurrence
$$\left\{\begin{matrix}
0 & if \quad x_i = 0 \quad or \quad y_j = 0\\ 
1 + L(i-1, j-1) & if \quad x_i = y_j\\ 
L(i, j-1) & if \quad x_i \neq y_j
\end{matrix}\right.$$

### Runtime analysis
This algorithm has two nested for loops of length n and m, therefore the runtime is as follows: $$O(nm)$$

In [12]:
def LCS_variant(x, y):
    n = len(x) + 1
    m = len(y) + 1
    
    L = np.zeros((n, m))
    
    for i in range(1, n):
        for j in range(1, m):
            if x[i-1] == y[j-1]:
                L[i, j] = 1 + L[i-1, j-1]
            else:
                L[i, j] = L[i, j-1]
    
    return L[:,-1].max()

In [13]:
x = ['a', 'b', 'd', 'b', 'a', 'b', 'f', 'g', 'd']
y = ['b', 'e', 't', 'f', 'd', 'b', 'f', 'a', 'f', 'r']

print(LCS_variant(x, y))

4.0


## Maximum Product
Given a string of integers Z = $z_1, z_2, ... , z_n$ and an integer $k$ where $0 \leq k < n$, maximize the mathematical result of the string by adding *exactly* $k$ operators. 

### Definition
Let P(i,k) be the maximum product made from $z_1, z_2, ... , z_i$ with k multiplication operators and where $z_i$ and $k$ are included. 

### Recurrence
$$\left\{\begin{matrix}
z(1:i) & if \quad k=0\\ 
0 & if \quad i \leq k\\ 
max_l\{z(l+1, i)*P(l,k-1): k \leq l < i\} & if \quad otherwise
\end{matrix}\right.$$

### Runtime analysis
This algorithm has three nested for loops of the following runtimes $O(n)$, $O(k)$, $O(n)$, therefore we have a final runtime of $$O(n^2k)$$

In [4]:
def maximum_product(z, k):
    n = len(z) + 1
    m = k+1
    
    P = np.zeros((n, m))
    P[1:, 0] = [int(z[:i+1]) for i in range(len(z))]
    
    for i in range(1, n):
        for j in range(1, m):
            if i > j:
                max_l = j
                for l in range(j, i):
                    if int(z[l:i]) * P[l, j-1] > int(z[max_l:i]) * P[max_l, j-1]:
                         max_l = l
                P[i, j] = int(z[max_l:i]) * P[max_l, j-1]
    
    return P[-1, -1]

In [5]:
z = str(84738)
k = 3

print(maximum_product(z, k))

18688.0


## Change coin variant
You are given denominations $x_1, x_2, ... , x_n$ and you want to make change for a value B. You can only use at most $k$ coins and use each denomination at most once. 

### Definition
Let C(i,b) = the minimum number of coins who add up to exactly $b_i$.

### Recurrence
$$\left\{\begin{matrix}
min\{C(i-1, b-x_i) + 1, C(i-1, b)\} & if \quad x_i \leq b\\ 
C(i-1,b) & if \quad x_i > b
\end{matrix}\right.$$

### Runtime analysis
$$O(nB)$$

In [27]:
def change_coins(x, k, B):
    n = len(x) + 1
    b = np.arange(B+1)
    
    C = np.zeros((n, len(b)))
    C[0, 1:] = 999  # 999 represents infinity in this algorithm
    
    for i in range(1, n):
        for j in range(1, len(b)):
            if x[i-1] > b[j]:
                C[i,j] = C[i-1, j]
            else:
                C[i,j] = min(C[i-1, j-x[i-1]]+1, C[i-1, j])
                
    if C[-1,-1] <= k:
        return True
    else: 
        return False

In [26]:
x = [2, 2, 1, 3, 1, 1]
k = 3
B = 7

print(change_coins(x, k, B))

[[   0.    0.    0.    0.    0.    0.    0.]
 [ 999.  999.  999.    1.    1.    1.    1.]
 [ 999.    1.    1.    1.    1.    1.    1.]
 [ 999.  999.  999.    2.    1.    1.    1.]
 [ 999.  999.    2.    2.    2.    2.    2.]
 [ 999.  999.  999.    3.    2.    2.    2.]
 [ 999.  999.  999.  999.    3.    3.    3.]
 [ 999.  999.  999.  999.    3.    3.    3.]]
True
