In [1]:
import pandas as pd
import numpy as np

In [3]:
x = ['a', 'b', 'd', 'b', 'a', 'b', 'f', 'g', 'd']
y = ['b', 'e', 't', 'f', 'd', 'b', 'f', 'a', 'f', 'r']

In [12]:
def LCS_variant(x, y):
    n = len(x) + 1
    m = len(y) + 1
    
    L = np.zeros((n, m))
    
    for i in range(1, n):
        for j in range(1, m):
            if x[i-1] == y[j-1]:
                L[i, j] = 1 + L[i-1, j-1]
            else:
                L[i, j] = L[i, j-1]
    
    max_i = 0
    for i in range(1,n):
        if L[i, -1] > L[max_i, -1]:
            max_i = i
    
    return L[max_i, -1]

In [13]:
print(LCS_variant(x, y))

4.0


In [22]:
z = str(84738)
k = 3

In [77]:
z[1:3]

'47'

In [80]:
def maximum_product(z, k):
    n = len(z) + 1
    m = k+1
    
    P = np.zeros((n, m))
    P[1:, 0] = [int(z[:i+1]) for i in range(len(z))]
    
    for i in range(1, n):
        for j in range(1, m):
            if i > j:
                max_l = j
                for l in range(j, i):
                    if int(z[l:i]) * P[l, j-1] > int(z[max_l:i]) * P[max_l, j-1]:
                         max_l = l
                P[i, j] = int(z[max_l:i]) * P[max_l, j-1]
    
    return P[-1, -1]

In [81]:
print(maximum_product(z, k))

18688.0


In [112]:
x = [10, 10, 20, 20, 5, 50]
k = 2
B = 55

In [114]:
def change_coins(x, k, B):
    n = len(x) + 1
    m = k + 1
    
    D = np.zeros((n, m))
    D[: , 0] = B  # base case
    D[0, :] = B  # base case
    
    for i in range(1, n):
        for j in range(1, m):
            minimum = abs((D[i-1, j-1] - x[i-1]))
            if D[i-1, j] < minimum:
                minimum = D[i-1, j]
            D[i, j] = minimum
    
    print(D.T)

In [115]:
print(change_coins(x, k, B))

[[ 55.  55.  55.  55.  55.  55.  55.]
 [ 55.  45.  45.  35.  35.  35.   5.]
 [ 55.  45.  35.  25.  15.  15.  15.]]
None
